/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainUI.java
 *
 * Created on Nov 22, 2012, 5:15:29 PM
 */
package startimport;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.io.File;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author benjakul
 */
public class mainUI extends javax.swing.JFrame {

    /** Creates new form mainUI */
    DefaultListModel listBib = new DefaultListModel();
    DefaultListModel matchList = new DefaultListModel();
    public mainUI() {
        initComponents();
        this.setSize(800, 600);
        this.setResizable(false);
        centreWindow(this);
        initObject();
    }
    private  void initObject (){
        jBT_browse.setSize(85, 36);    
        jBT_mainbibpath.setSize(85, 36); 
        jTF_mainfilepath.setSize(603, 25);
        jTF_mainbibpath.setSize(603, 25);
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTF_mainfilepath = new javax.swing.JTextField();
        jBT_browse = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTF_mainbibpath = new javax.swing.JTextField();
        jBT_mainbibpath = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jL_biblist = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jL_matchlist = new javax.swing.JList();
        jBT_save = new javax.swing.JButton();
        jLB_savepath = new javax.swing.JLabel();
        jLB_remain = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setBackground(new java.awt.Color(0, 102, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Main File Path");

        jTF_mainfilepath.setBorder(null);
        jTF_mainfilepath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_mainfilepathActionPerformed(evt);
            }
        });

        jBT_browse.setBackground(new java.awt.Color(51, 51, 51));
        jBT_browse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBT_browseMouseClicked(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Browse");

        javax.swing.GroupLayout jBT_browseLayout = new javax.swing.GroupLayout(jBT_browse);
        jBT_browse.setLayout(jBT_browseLayout);
        jBT_browseLayout.setHorizontalGroup(
            jBT_browseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBT_browseLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jBT_browseLayout.setVerticalGroup(
            jBT_browseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Main bib Path");

        jTF_mainbibpath.setBorder(null);

        jBT_mainbibpath.setBackground(new java.awt.Color(51, 51, 51));
        jBT_mainbibpath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBT_mainbibpathMouseClicked(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Browse");

        javax.swing.GroupLayout jBT_mainbibpathLayout = new javax.swing.GroupLayout(jBT_mainbibpath);
        jBT_mainbibpath.setLayout(jBT_mainbibpathLayout);
        jBT_mainbibpathLayout.setHorizontalGroup(
            jBT_mainbibpathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBT_mainbibpathLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jBT_mainbibpathLayout.setVerticalGroup(
            jBT_mainbibpathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        jL_biblist.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jL_biblistPropertyChange(evt);
            }
        });
        jL_biblist.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jL_biblistVetoableChange(evt);
            }
        });
        jScrollPane1.setViewportView(jL_biblist);

        jScrollPane2.setViewportView(jL_matchlist);

        jBT_save.setText("Save");
        jBT_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBT_saveMouseClicked(evt);
            }
        });

        jLB_savepath.setForeground(new java.awt.Color(255, 255, 255));
        jLB_savepath.setText("   ");

        jLB_remain.setForeground(new java.awt.Color(255, 255, 255));
        jLB_remain.setText("0");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("File In List");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTF_mainbibpath, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBT_mainbibpath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                            .addComponent(jTF_mainfilepath, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBT_browse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLB_remain, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel5))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLB_savepath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 714, Short.MAX_VALUE)
                        .addComponent(jBT_save)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTF_mainbibpath, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBT_mainbibpath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLB_remain)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBT_browse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTF_mainfilepath, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBT_save)
                    .addComponent(jLB_savepath))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTF_mainfilepathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_mainfilepathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_mainfilepathActionPerformed

    private void jBT_browseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBT_browseMouseClicked
        if(chooseDialog(jTF_mainfilepath)){
            
            ReadExcelFile readEF = new ReadExcelFile();
            
            String filepath = jTF_mainfilepath.getText();
            int sSize = readEF.getSheetsSize(filepath);
            jLB_savepath.setText(sSize+"");
            int size = jL_biblist.getModel().getSize();
                ArrayList<String> aLBib = new ArrayList<String>();
                for (int i=0; i < size; i++){
                    String getBib = jL_biblist.getModel().getElementAt(i).toString();
                    aLBib.add(getBib);
                }
                
            for (int k = 0 ; k < sSize ; k++){
                matchList.clear();
                ArrayList<List<String>> iVec = readEF.ReadExcel(filepath,k);               
                ArrayList<String> nVec=  readEF.matchBibNo(iVec,aLBib);
                for (int i = 0 ;i < nVec.size();i++){
                    matchList.addElement(nVec.get(i));
                }
                jL_matchlist.removeAll();
                jL_matchlist.setModel(matchList);
                jLB_savepath.setText(k+"");
                ArrayList<String> saveObj  = getALfromList(jL_matchlist);
                WriteText wt = new WriteText();
                wt.write(saveObj, "C:\\Users\\9119\\Documents\\"+(k+1)+".csv");
                
            }
       }
        
    }//GEN-LAST:event_jBT_browseMouseClicked

    private void jBT_mainbibpathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBT_mainbibpathMouseClicked
        if(chooseDialog(jTF_mainbibpath)){
            ReadExcelFile readEF = new ReadExcelFile(); 
            String filepath = jTF_mainbibpath.getText();//.replace("\\","//");
            ArrayList<List<String>> iVec = readEF.ReadExcel(filepath);
            ArrayList<String> nVec=  readEF.chkBibNo(iVec);
            for (int i = 0 ;i < nVec.size();i++){
                listBib.addElement(nVec.get(i));
            }
            //listBib.addElement(nVec);
            jL_biblist.setModel(listBib);
            
        }
    }//GEN-LAST:event_jBT_mainbibpathMouseClicked

    private void jL_biblistVetoableChange(java.beans.PropertyChangeEvent evt) throws java.beans.PropertyVetoException {//GEN-FIRST:event_jL_biblistVetoableChange
        
        ///
    }//GEN-LAST:event_jL_biblistVetoableChange

    private void jL_biblistPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jL_biblistPropertyChange
        jLB_remain.setText(jL_biblist.getModel().getSize()+"");
    }//GEN-LAST:event_jL_biblistPropertyChange

    private void jBT_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBT_saveMouseClicked
           ArrayList<String> saveObj  = getALfromList(jL_matchlist);     
           WriteText wt = new WriteText();
           wt.write(saveObj, "C:\\Users\\9119\\Documents\\testsave.csv");
           JOptionPane.showMessageDialog(rootPane, "Save Successfully");
        
    }//GEN-LAST:event_jBT_saveMouseClicked
    private ArrayList<String> getALfromList (JList jL){
        ArrayList<String> aLObj = new ArrayList<String>();
            int size = jL.getModel().getSize();               
                for (int i=0; i < size; i++){
                    String getBib = jL.getModel().getElementAt(i).toString();
                    aLObj.add(getBib);
                }
        
        return   aLObj;
    }
    public  boolean chooseDialog(JTextField jTF){
        try{
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);                   
        if (chooser.getSelectedFile().length()>0){
            File file = chooser.getSelectedFile(); 
            String filename = file.getAbsolutePath();
            jTF.setText(filename);
            return true;
        }
        else{
            return false;
            }
        }
        catch (Exception e){
            return false;
        }
  
    }
    public  boolean chooseDialog(JLabel jLB){
        try{
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);                   
        if (chooser.getSelectedFile().length()>0){
            File file = chooser.getSelectedFile(); 
            String filename = file.getAbsolutePath();
            jLB.setText(filename);
            return true;
        }
        else{
            return false;
            }
        }
        catch (Exception e){
            return false;
        }
  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }
    public void runUI (){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBT_browse;
    private javax.swing.JPanel jBT_mainbibpath;
    private javax.swing.JButton jBT_save;
    private javax.swing.JLabel jLB_remain;
    private javax.swing.JLabel jLB_savepath;
    private javax.swing.JList jL_biblist;
    private javax.swing.JList jL_matchlist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTF_mainbibpath;
    private javax.swing.JTextField jTF_mainfilepath;
    // End of variables declaration//GEN-END:variables

    public static void centreWindow(Window frame) {
    Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
    int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
    int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
    frame.setLocation(x, y);
    }
}
